# Rule-based reward system configuration for Phase A

# Rule weights (sum to 1.0)
weights:
  length_constraint: 0.2
  entity_overlap: 0.2
  number_consistency: 0.15
  profanity_penalty: 0.05
  fluency: 0.05
  bart_mnli_factual_consistency: 0.35

# Length constraint settings
length:
  min_words: 20
  max_words: 200
  optimal_range: [30, 120]
  penalty_factor: 0.5

# Entity overlap settings
entity:
  min_overlap: 0.3
  optimal_overlap: 0.7
  overlap_threshold: 0.5

# Number consistency
numbers:
  exact_match_bonus: 1.0
  partial_match_bonus: 0.5
  mismatch_penalty: -0.5

# Profanity detection
profanity:
  enabled: true
  penalty: -1.0
  wordlist_path: null  # Use default wordlist

# Fluency scoring
fluency:
  enabled: true
  min_score: 0.5
  model_name: null  # Use default model

# BART-MNLI specific configuration
bart_mnli:
  threshold: 0.8            # Entailment probability threshold for binary scoring
  max_length: 1024          # Maximum sequence length (words) for truncation
  device: "cuda"            # Device: "cuda", "cpu", or "auto"
