# Hydra configuration

run:
  dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

sweep:
  dir: ./outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
  subdir: ${hydra.job.num}

job:
  name: rlvr_summary
  chdir: false

# Override default hydra config
hydra:
  output_subdir: .hydra
  run:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ./outputs/multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}