# Main configuration file for RLVR Summary
# This file defines the default configuration structure

defaults:
  - model: distilgpt2
  - training: ppo_baseline
  - data: cnn_dailymail
  - rewards: rule_bundle
  - evaluation: default
  - experiment: default
  - hydra: default
  - _self_

# Project settings
project:
  name: "rlvr-summary"
  version: "0.1.0"
  description: "Tool-augmented summarizer using RL-VR"

# Paths
paths:
  data_dir: "./data"
  output_dir: "./outputs"
  log_dir: "./logs"
  checkpoint_dir: "./checkpoints"

# Experiment tracking
wandb:
  enabled: false
  project: "rlvr-summary"
  entity: null  # Set your W&B entity here
  group: null
  tags: []
  notes: ""

# Global settings
seed: 42
device: "auto"  # "auto", "cpu", "cuda", "mps"
debug: false
