# VERL PPO Configuration for RLVR Summary
# Based on official VERL ppo_trainer.yaml

# Dataset configuration
data:
  tokenizer: null
  use_shm: False
  train_files: []  # Will be populated by data preparation script
  val_files: []    # Will be populated by data preparation script
  prompt_key: prompt
  reward_fn_key: data_source
  max_prompt_length: 256
  max_response_length: 256
  train_batch_size: 4
  val_batch_size: null
  return_raw_input_ids: False
  return_raw_chat: False
  return_full_prompt: False
  shuffle: True
  validation_shuffle: False
  filter_overlong_prompts: False
  filter_overlong_prompts_workers: 1
  truncation: error
  image_key: images
  video_key: videos
  trust_remote_code: False
  custom_cls:
    path: null
    name: null

# Actor/Rollout/Reference model configuration
actor_rollout_ref:
  hybrid_engine: true
  
  model:
    path: distilgpt2
    custom_chat_template: null
    use_shm: false
    external_lib: null
    override_config: {}
    enable_gradient_checkpointing: false
    enable_activation_offload: false
    use_remove_padding: false
    lora_rank: 0
    lora_alpha: 16
    target_modules: all-linear
    exclude_modules: null
    use_liger: false
    use_fused_kernels: false
    fused_kernel_options:
      impl_backend: torch
    trust_remote_code: false
  
  actor:
    strategy: fsdp
    ppo_mini_batch_size: 4
    ppo_micro_batch_size: null
    ppo_micro_batch_size_per_gpu: 2
    use_dynamic_bsz: false
    ppo_max_token_len_per_gpu: 512  # max_prompt_length + max_response_length
    grad_clip: 1.0
    clip_ratio: 0.2
    clip_ratio_low: 0.2
    clip_ratio_high: 0.2
    policy_loss:
      loss_mode: vanilla
      clip_cov_ratio: 0.0002
      clip_cov_lb: 1.0
      clip_cov_ub: 5.0
      kl_cov_ratio: 0.0002
      ppo_kl_coef: 0.1
    clip_ratio_c: 3.0
    loss_agg_mode: token-mean
    entropy_coeff: 0.01
    use_kl_loss: false
    use_torch_compile: false
    kl_loss_coef: 0.001
    kl_loss_type: low_var_kl
    ppo_epochs: 4
    shuffle: false
    ulysses_sequence_parallel_size: 1
    entropy_from_logits_with_chunking: False
    entropy_checkpointing: False
    checkpoint:
      save_contents: ['model', 'optimizer', 'extra']
      load_contents: ['model', 'optimizer', 'extra']
    optim:
      lr: 1.41e-5
      lr_warmup_steps: 100
      lr_warmup_steps_ratio: 0.01
      min_lr_ratio: 0.0
      num_cycles: 0.5
      warmup_style: constant
      total_training_steps: 10000
      weight_decay: 0.01
    fsdp_config:
      wrap_policy:
        min_num_params: 0
      param_offload: false
      optimizer_offload: false
      offload_policy: false
      reshard_after_forward: true
      fsdp_size: -1
      forward_prefetch: False
    profiler:
      discrete: False
      all_ranks: False
      ranks: null
  
  ref:
    strategy: fsdp
    fsdp_config:
      param_offload: false
      reshard_after_forward: true
      forward_prefetch: False
      wrap_policy:
        min_num_params: 0
    use_torch_compile: false
    log_prob_micro_batch_size: null
    log_prob_micro_batch_size_per_gpu: 4
    log_prob_use_dynamic_bsz: false
    log_prob_max_token_len_per_gpu: 512
    ulysses_sequence_parallel_size: 1
    entropy_from_logits_with_chunking: False
    entropy_checkpointing: False
    profiler:
      discrete: False
      all_ranks: False
      ranks: null
  
  rollout:
    name: hf  # Use HuggingFace for simpler setup
    mode: sync
    temperature: 0.7
    top_k: 0
    top_p: 0.9
    prompt_length: 256
    response_length: 256
    dtype: float32
    gpu_memory_utilization: 0.5
    ignore_eos: False
    enforce_eager: True
    free_cache_engine: True
    load_format: dummy_dtensor
    layered_summon: False
    tensor_model_parallel_size: 1
    max_num_batched_tokens: 8192
    max_model_len: null
    max_num_seqs: 1024
    log_prob_micro_batch_size: null
    log_prob_micro_batch_size_per_gpu: 4
    log_prob_use_dynamic_bsz: false
    log_prob_max_token_len_per_gpu: 512
    disable_log_stats: True
    enable_chunked_prefill: True
    do_sample: True
    n: 1
    multi_stage_wake_up: false
    engine_kwargs:
      vllm:
        swap_space: null
        disable_mm_preprocessor_cache: False
      sglang:
        attention_backend: null
    val_kwargs:
      top_k: 0
      top_p: 1.0
      temperature: 0
      n: 1
      do_sample: False
    multi_turn:
      enable: False
      max_assistant_turns: null
      tool_config_path: null
      max_user_turns: null
      max_parallel_calls: 1
      max_tool_response_length: 256
      tool_response_truncate_side: middle
      interaction_config_path: null
      completion_callback: null
      use_inference_chat_template: False
      tokenization_sanity_check_mode: strict
      format: hermes
    calculate_log_probs: False
    profiler:
      discrete: False
      all_ranks: False
      ranks: null
    agent:
      num_workers: 8
      custom_async_server:
        path: null
        name: null

# Critic model configuration
critic:
  rollout_n: 1
  strategy: fsdp
  optim:
    lr: 1.41e-5
    lr_warmup_steps_ratio: 0.01
    min_lr_ratio: null
    warmup_style: constant
    total_training_steps: -1
    weight_decay: 0.01
  model:
    path: distilgpt2
    use_shm: False
    tokenizer_path: distilgpt2
    override_config: {}
    external_lib: null
    enable_gradient_checkpointing: True
    enable_activation_offload: False
    use_remove_padding: False
    trust_remote_code: false
    fsdp_config:
      param_offload: False
      optimizer_offload: False
      offload_policy: False
      reshard_after_forward: True
      wrap_policy:
        min_num_params: 0
      fsdp_size: -1
      forward_prefetch: False
    lora_rank: 0
    lora_alpha: 16
    target_modules: all-linear
  ppo_mini_batch_size: 4
  ppo_micro_batch_size: null
  ppo_micro_batch_size_per_gpu: 2
  forward_micro_batch_size: 4
  forward_micro_batch_size_per_gpu: 2
  use_dynamic_bsz: false
  ppo_max_token_len_per_gpu: 1024  # Doubled for critic
  forward_max_token_len_per_gpu: 1024
  ulysses_sequence_parallel_size: 1
  ppo_epochs: 4
  shuffle: false
  grad_clip: 1.0
  cliprange_value: 0.5
  loss_agg_mode: token-mean
  checkpoint:
    save_contents: ['model', 'optimizer', 'extra']
    load_contents: ['model', 'optimizer', 'extra']
  profiler:
    discrete: False
    all_ranks: False
    ranks: null

# Reward model configuration (disabled for rule-based rewards)
reward_model:
  enable: False
  strategy: fsdp
  model:
    input_tokenizer: distilgpt2
    path: ~/models/reward-model
    use_shm: False
    external_lib: null
    use_remove_padding: False
    use_fused_kernels: false
    trust_remote_code: False
    fsdp_config:
      wrap_policy:
        min_num_params: 0
      param_offload: False
      reshard_after_forward: True
      fsdp_size: -1
      forward_prefetch: False
  micro_batch_size: null
  micro_batch_size_per_gpu: null
  max_length: null
  ulysses_sequence_parallel_size: 1
  use_dynamic_bsz: false
  forward_max_token_len_per_gpu: 1024
  reward_manager: naive
  launch_reward_fn_async: False
  sandbox_fusion:
    url: null
    max_concurrent: 64
    memory_limit_mb: 1024
  profiler:
    discrete: False
    all_ranks: False
    ranks: null

# Custom reward function configuration
custom_reward_function:
  path: null  # Will be set by training script
  name: compute_score

# Algorithm configuration
algorithm:
  gamma: 1.0
  lam: 1.0
  adv_estimator: gae
  norm_adv_by_std_in_grpo: True
  use_kl_in_reward: False
  kl_penalty: kl
  kl_ctrl:
    type: fixed
    kl_coef: 0.1
    horizon: 10000
    target_kl: 0.1
  use_pf_ppo: False
  pf_ppo:
    reweight_method: pow
    weight_pow: 2.0

# Trainer configuration
trainer:
  balance_batch: True
  total_epochs: 1
  total_training_steps: null
  profile_steps: null
  controller_nsight_options:
    trace: "cuda,nvtx,cublas,ucx"
    cuda-memory-usage: "true"
    cuda-graph-trace: "graph"
  worker_nsight_options:
    trace: "cuda,nvtx,cublas,ucx"
    cuda-memory-usage: "true"
    cuda-graph-trace: "graph"
    capture-range: "cudaProfilerApi"
    capture-range-end: null
    kill: none
  project_name: rlvr_summary
  experiment_name: ppo_baseline
  logger: ['console', 'wandb']
  log_val_generations: 0
  rollout_data_dir: null
  validation_data_dir: null
  nnodes: 1
  n_gpus_per_node: 1
  save_freq: 1000
  esi_redundant_time: 0
  resume_mode: auto
  resume_from_path: null
  val_before_train: False
  val_only: False
  test_freq: 500
  critic_warmup: 0
  default_hdfs_dir: null
  del_local_ckpt_after_load: False
  default_local_dir: ./checkpoints
  max_actor_ckpt_to_keep: null
  max_critic_ckpt_to_keep: null
  ray_wait_register_center_timeout: 300
  device: cuda

# Ray initialization configuration
ray_init:
  num_cpus: null
  timeline_json_file: null
